// <auto-generated />
namespace SolidWaste.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class junichi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(junichi));
        
        string IMigrationMetadata.Id
        {
            get { return "201612262138214_junichi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
